"""add fpe_settings table

Revision ID: 67c1c76a6714
Revises: f1ab8c9e9974
Create Date: 2026-03-28 17:29:01.040670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c1c76a6714'
down_revision: Union[str, Sequence[str], None] = 'f1ab8c9e9974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpe_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('default_tweak', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fpe_settings')
    # ### end Alembic commands ###
