"""add report_only to rule_sets, status to interactions

Revision ID: e67f8cada254
Revises: a63bb85b150b
Create Date: 2026-03-28 14:59:03.451156

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e67f8cada254'
down_revision: str | Sequence[str] | None = 'a63bb85b150b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('rule_sets', sa.Column('report_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_sets', 'report_only')
    op.drop_column('interactions', 'status')
    # ### end Alembic commands ###
